# Generated by Django 4.2.20 on 2025-04-08 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('endpoint', models.SlugField(unique=True)),
                ('success_response', models.JSONField()),
                ('error_response', models.JSONField()),
                ('validations', models.JSONField(blank=True, default=dict)),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('returned_status', models.IntegerField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customapi')),
            ],
        ),
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customapi')),
            ],
        ),
    ]
