# Generated by Django 4.2.20 on 2025-04-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customapi_hitlog_apidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='auto_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
