# Generated by Django 4.2.20 on 2025-04-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mockapi_header_mockapi_query_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockapi',
            name='query_params',
        ),
        migrations.CreateModel(
            name='QueryMockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_params', models.JSONField(default=dict, null=True)),
                ('header', models.JSONField(default=dict, null=True)),
                ('response_msg', models.JSONField(null=True)),
                ('response_code', models.IntegerField(null=True)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mockapi')),
            ],
        ),
    ]
