# Generated by Django 4.2.20 on 2025-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_mockapi_query_params_querymockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockapi',
            name='api_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
