# Generated by Django 4.2.20 on 2025-04-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mockapi_api_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymockdata',
            name='api_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
