# Generated by Django 4.2.20 on 2025-04-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_querymockdata_api_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockapi',
            name='api_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='querymockdata',
            name='api_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, null=True),
        ),
    ]
