# Generated by Django 4.2.20 on 2025-04-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_mockapi_api_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymockdata',
            name='mock',
        ),
        migrations.DeleteModel(
            name='MockApi',
        ),
        migrations.DeleteModel(
            name='QueryMockData',
        ),
    ]
