# Generated by Django 4.2.20 on 2025-04-11 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_querymockdata_mock_delete_mockapi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mock_endpoint', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('body', models.JSONField(default=dict, null=True)),
                ('response_header', models.JSONField(null=True)),
                ('response_msg', models.JSONField()),
                ('response_code', models.IntegerField(choices=[(100, 100), (101, 101), (102, 102), (103, 103), (200, 200), (201, 201), (202, 202), (203, 203), (204, 204), (205, 205), (206, 206), (207, 207), (208, 208), (226, 226), (300, 300), (301, 301), (302, 302), (303, 303), (304, 304), (305, 305), (306, 306), (307, 307), (308, 308), (400, 400), (401, 401), (402, 402), (403, 403), (404, 404), (405, 405), (406, 406), (407, 407), (408, 408), (409, 409), (410, 410), (411, 411), (412, 412), (413, 413), (414, 414), (415, 415), (416, 416), (417, 417), (418, 418), (421, 421), (422, 422), (423, 423), (424, 424), (425, 425), (426, 426), (428, 428), (429, 429), (431, 431), (451, 451), (500, 500), (501, 501), (502, 502), (503, 503), (504, 504), (505, 505), (506, 506), (507, 507), (508, 508), (510, 510), (511, 511)])),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mock')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mockdata',
            constraint=models.UniqueConstraint(fields=('api', 'method', 'body'), name='unique_user_post'),
        ),
    ]
