# Generated by Django 4.2.20 on 2025-04-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mock_mockdata_mockdata_unique_user_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=256)),
                ('ip_addredd', models.CharField(max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
