# Generated by Django 4.2.20 on 2025-04-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_request_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_logs',
            old_name='ip_addredd',
            new_name='ip_address',
        ),
    ]
