# Generated by Django 4.2.20 on 2025-04-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_ip_addredd_request_logs_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_logs',
            old_name='method',
            new_name='req_method',
        ),
        migrations.RenameField(
            model_name='request_logs',
            old_name='user',
            new_name='req_user',
        ),
    ]
