# Generated by Django 4.2.20 on 2025-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_method_request_logs_req_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
