# Generated by Django 4.2.20 on 2025-04-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_mock_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mock',
            old_name='public',
            new_name='public_access',
        ),
    ]
