# Generated by Django 4.2.20 on 2025-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_public_mock_public_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockdata',
            name='query_params',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
