# Generated by Django 4.2.20 on 2025-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=50)),
                ('success_code', models.CharField(max_length=20)),
                ('error_code', models.CharField(max_length=20)),
                ('endpoint_description', models.TextField()),
                ('endpoint_url', models.CharField(max_length=250)),
            ],
        ),
    ]
